# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='cropgrown',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='land_size',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='moisture_content',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='place',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pressure',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='water_level',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='weatherdescription',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='rain',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
